include(UtilityMacros)

find_package(CUDA REQUIRED)

set(NWXCUDA_LIBRARIES ${CUDA_LIBRARIES}) 
set(NWXCUDA_INCLUDE_DIRS ${CUDA_INCLUDE_DIRS})
set(NWXCUDA_DEFINITIONS "-DTAMM_CUDA")
set(NWXCUDA_FOUND TRUE)

