bundle_cmake_args(PYBIND11_PYTHON PYTHON_INCLUDE_DIRS PYTHON_LIBRARIES)

set(PYBIND_GIT_TAG 8dcced29ae4c7654c25bc50742a72556ee3ae36c)
if(ENABLE_DEV_MODE)
  set(PYBIND_GIT_TAG master)
endif()

ExternalProject_Add(pybind11_External
    GIT_REPOSITORY https://github.com/pybind/pybind11
    GIT_TAG ${PYBIND_GIT_TAG}
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS}
               ${PYBIND11_PYTHON}
               -DPYBIND11_TEST=FALSE
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
)

