
set(MSGSL_GIT_TAG 10df83d292bf5bbdc487e57dc8c2dc8c7a01f4d1)
if(ENABLE_DEV_MODE)
  set(MSGSL_GIT_TAG main)
endif()

ExternalProject_Add(MSGSL_External
    GIT_REPOSITORY https://github.com/Microsoft/GSL.git
    GIT_TAG ${MSGSL_GIT_TAG}
    UPDATE_DISCONNECTED 1
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DGSL_TEST=OFF
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)

