
set(TALSH_GIT_TAG 9d7ac81fef8dfde7c17c9cfddfd3c4705a2be506)
if(ENABLE_DEV_MODE)
  set(TALSH_GIT_TAG master)
endif()

ExternalProject_Add(TALSH_External
    GIT_REPOSITORY https://github.com/ajaypanyala/TAL_SH.git
    GIT_TAG ${TALSH_GIT_TAG}
    UPDATE_DISCONNECTED 1
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DUSE_OPENMP=${USE_OPENMP} -DUSE_HIP=${USE_HIP}
    -DTALSH_GPU=ON -DTALSH_GPU_ARCH=${NV_GPU_ARCH} -DWITH_CUTENSOR=${USE_CUTENSOR} 
    -DCUTENSOR_ROOT=${CUTENSOR_INSTALL_PREFIX} -DROCM_ROOT=${ROCM_ROOT}
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)

