
set(LIBRETT_GIT_TAG bc29bcba71c2ee7e9cf65d51ddb67df8ff9a2ed0)
if(ENABLE_DEV_MODE)
  set(LIBRETT_GIT_TAG master)
endif()

if(USE_DPCPP)
  set(LIBRETT_GIT_TAG master)
endif()

ExternalProject_Add(Librett_External
    GIT_REPOSITORY https://github.com/victor-anisimov/Librett.git
    GIT_TAG ${LIBRETT_GIT_TAG}
    UPDATE_DISCONNECTED 1
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DENABLE_SYCL=${USE_DPCPP}
    -DENABLE_CUDA=${USE_CUDA} -DENABLE_HIP=${USE_HIP} -DCMAKE_CUDA_ARCHITECTURES=${GPU_ARCH} 
    -DROCM_PATH=${ROCM_ROOT} -DENABLE_TESTS=OFF
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)

#    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DENABLE_SYCL=${USE_DPCPP}
#    -DENABLE_CUDA=${USE_CUDA} -DENABLE_HIP=${USE_HIP} -DCMAKE_CUDA_ARCHITECTURES=${GPU_ARCH} 
#    -DROCM_ROOT=${ROCM_ROOT} -DENABLE_SYCL_CUDA=${ENABLE_SYCL_CUDA} -DENABLE_SYCL_HIP=${ENABLE_SYCL_HIP} 
#    -DCMAKE_HIP_ARCHITECTURES=${GPU_ARCH} -DCUDA_ROOT=${CUDA_ROOT} -DENABLE_TESTS=OFF

