include(${CMAKE_CURRENT_LIST_DIR}/dep_versions.cmake)

if(ENABLE_OFFLINE_BUILD)
ExternalProject_Add(HPTT_External
    URL ${DEPS_LOCAL_PATH}/hptt
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DENABLE_OPENMP=${USE_OPENMP} -DMARCH_FLAGS=${MARCH_FLAGS}
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)
else()
ExternalProject_Add(HPTT_External
    GIT_REPOSITORY https://github.com/ajaypanyala/hptt.git
    GIT_TAG ${HPTT_GIT_TAG}
    UPDATE_DISCONNECTED 1
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DENABLE_OPENMP=${USE_OPENMP} -DMARCH_FLAGS=${MARCH_FLAGS}
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)
endif()

