
set(MSGSL_GIT_TAG 3ba80d5dd465828909e1ee756b8c437d5e820ccc)
if(ENABLE_DEV_MODE)
  set(MSGSL_GIT_TAG main)
endif()

if(ENABLE_LOCAL_BUILD)
ExternalProject_Add(MSGSL_External
    URL ${LOCAL_BUILD_PATH}/GSL
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DGSL_TEST=OFF
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)
else()
ExternalProject_Add(MSGSL_External
    GIT_REPOSITORY https://github.com/Microsoft/GSL.git
    GIT_TAG ${MSGSL_GIT_TAG}
    UPDATE_DISCONNECTED 1
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DGSL_TEST=OFF
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)
endif()
