ExternalProject_Add(cereal_External
    GIT_REPOSITORY https://github.com/USCiLab/cereal
    GIT_TAG 1de8fe89471d69ea392ea260ce74e079d5f4b415
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS}
               -DSKIP_PORTABILITY_TEST=TRUE
               -DJUST_INSTALL_CEREAL=TRUE
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
)

