ExternalProject_Add(cereal_External
    GIT_REPOSITORY https://github.com/USCiLab/cereal
    GIT_TAG 46a4a910077bf9e9f8327c8f6ea761c89b06da53
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS}
               -DSKIP_PORTABILITY_TEST=TRUE
               -DJUST_INSTALL_CEREAL=TRUE
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
)

