

set(HPTT_GIT_TAG bf4fa878524d1e99bd7afa1b6c1807ff0fab4e7b)
if(ENABLE_DEV_MODE)
    set(HPTT_GIT_TAG master)
endif()

ExternalProject_Add(HPTT_External
    GIT_REPOSITORY https://github.com/ajaypanyala/hptt.git
    GIT_TAG ${HPTT_GIT_TAG}
    UPDATE_DISCONNECTED 1
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DENABLE_OPENMP=${USE_OPENMP}
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)

